core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('',views.core, name="teams-page"),
    path('all/',views.jsonitems,name="core-info"),
]

events/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "events"

urlpatterns = [
    path('',views.ourevents,name='ourevents'),
    path('liveupdates/',views.liveupdates,name='liveupdates'),
    path('pingo/',views.pingo,name='pingo'),
    path('<str:dept>/',views.eachevent,name="event-view")
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home,name='landing-page'),
]

sponsors/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.sponsors,name='sponsors-page'),
]

taqneeq13/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('hvp/admin/', admin.site.urls),
    path('',include('main.urls')),
    path('core/',include('core.urls')),
    path('events/',include('events.urls')),
    path('sponsors/',include('sponsors.urls')),
]

core/models.py
from django.db import models

# Create your models here.


class Member(models.Model):
    name = models.CharField(max_length=200, blank=True)
    position = models.CharField(max_length=200, blank=True)
    deptName = models.CharField(max_length=200, blank=True)
    desc = models.TextField(max_length=400, blank=True)
    posnum = models.CharField(max_length=10, blank=True)
    gifurl = models.URLField(max_length=100000000000000000000000000000000, blank=True)

    def __str__(self):
        return self.name + f' ({self.deptName})'

    # def get_model_fields(self,model):
    #     return model._meta.fields

events/models.py
from django.db import models

# Create your models here.

class Event(models.Model):
    name = models.CharField(max_length=200, blank=True)
    deptName = models.CharField(max_length=200, blank=True)
    desc = models.TextField(max_length=10000000, blank=True)
    formurl = models.URLField(max_length=100000000000, blank=True)
    ongoingurl = models.URLField(max_length=100000000000, blank=True)
    ongoing = models.BooleanField(null=True, default= False)
    contact = models.CharField(max_length=10,default='9820050976', blank=True)

    def __str__(self):
        return self.name + f' ({self.deptName}) -- ' + str(self.ongoing)

main/models.py
from django.db import models

# Create your models here.

sponsors/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse
from .models import Member
import json
app_name = "core"

# Create your views here.

def jsonitems(request):
    coreinfo = serializers.serialize("json",Member.objects.all().filter().order_by('posnum','position','name'))
    coreinfo = json.loads(coreinfo)
    return JsonResponse(coreinfo,safe=False)

def core(request):
    return render(request, 'core/core.html')

events/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse
from .models import Event
import json

# Create your views here.

def jsonitems(request,dept):
    eventinfo = serializers.serialize("json",Event.objects.all().filter(deptName__icontains=dept).order_by('name'))
    eventinfo = json.loads(eventinfo)
    return JsonResponse(eventinfo,safe=False)

def ourevents(request):
    return render(request,'events/events.html',{})


def eachevent(request,dept):
    e = Event.objects.all().filter(deptName__icontains=dept).order_by('name')
    return render(request,'events/event-content.html',{'events':e, 'dept': e[0].deptName})

def liveupdates(request):
    e = Event.objects.all().filter(ongoing=True).order_by('name')
    return render(request,'events/liveupdate.html',{'events':e})


def pingo(request):
    return render(request,'events/bingo.html')

main/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'main/index.html',{})

sponsors/views.py
from django.shortcuts import render

# Create your views here.

def sponsors(request):
    return render(request,'sponsors/sponsors.html',{})

core/templates/core/core.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Our Team | Taqneeq13.0</title>
    <!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

    <link rel="shortcut icon" href="{% static 'img/tq_logo.png' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" />
    <!-- <link rel="stylesheet" href="{% static '/css/semantic.min.css' %}"> -->
    <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static '/css/custom.css' %}">
    <link rel="stylesheet" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static '/css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/core.css' %}">

    <style>
        .menu-main::before {
            top: 28.5%;
        }
        
        .space {
            z-index: -1;
        }
        
        @media only screen and (max-width: 480px) {
            .rectangle {
                bottom: 4vw;
            }
            #FOOTER {
                bottom: 13vw;
            }
        }
    </style>

</head>

<body onload="getcore()">
    <div class="space"></div>

    <div class="headerspace"></div>

    <!-- <a href="#" class="no-line logotype"><img src="{% static 'img/tq_logo.png' %}" alt="" class="tqSmallLogo"></a> -->

    <!-- Menu -->
    <nav>
        <div class="menu-main">
            <div class="bar1 longanimnd"></div>
            <div class="bar2 longanimnd2"></div>
            <div class="bar3 longanimnd3"></div>
        </div>
        <ul class="nav-links">
            <li id="li1"><a class=" menuAfterClick1" href="{% url 'main:landing-page' %}">Home</a></li>
            <li>
                <a class="menuAfterClick3" href="#"></a>
            </li>
            <li><a class="menuAfterClick4" href="{% url 'events:ourevents' %}"> Events</a></li>
            <li><a class="menuAfterClick2" href="{% url 'events:liveupdates' %}">Event Schedule</a></li>

            <!-- <li><a class="menuAfterClick5" href="#con">Contact Us</a></li> -->
            <li>
                <a class="menuAfterClick5" href="#"></a>
            </li>
            <li><a class="menuAfterClick6" href="{% url 'core:teams-page' %}">Our Team</a></li>
            <li>
                <a class="menuAfterClick7" href="#"></a>
            </li>
        </ul>
        <script src="{% static 'js/menu.js' %}"></script>
    </nav>
    <!-- Menu -->

    <div class="coresegment" style="overflow-x:hidden;">
        <div class="ui top attached tabular menu" id="coreTab">
            <a class="item active" data-tab="Supercore">Super Core</a>
            <a class="item" data-tab="Admin">Admin</a>
            <a class="item" data-tab="AGM">Artist & Guest Management</a>
            <a class="item" data-tab="DC">Digital Creatives</a>
            <a class="item" data-tab="Events">Events</a>
            <a class="item" data-tab="Informals">Informals</a>
            <a class="item" data-tab="Logistics">Logistics</a>
            <a class="item" data-tab="Marketing">Marketing</a>
            <a class="item" data-tab="Photography">Photography</a>
            <a class="item" data-tab="Publicity">Publicity</a>
            <a class="item" data-tab="SMCW">Social Media & Content Writing</a>
            <a class="item" data-tab="Workshops">Workshops</a>
            <a class="item" data-tab="TS">Tech Support</a>
        </div>

        <div class="ui bottom attached tab segment active" data-tab="Supercore">
            <div class="core-grid" id="Supercore">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Admin">
            <div class="core-grid" id="Admin">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="AGM">
            <div class="core-grid" id="AGM">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="DC">
            <div class="core-grid" id="DC">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Events">
            <div class="core-grid" id="Events">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Informals">
            <div class="core-grid" id="Informals">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Logistics">
            <div class="core-grid" id="Logistics">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Marketing">
            <div class="core-grid" id="Marketing">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Photography">
            <div class="core-grid" id="Photography">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Publicity">
            <div class="core-grid" id="Publicity">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="SMCW">
            <div class="core-grid" id="SMCW">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="Workshops">
            <div class="core-grid" id="Workshops">
            </div>
        </div>

        <div class="ui bottom attached tab segment" data-tab="TS">
            <div class="core-grid" id="TS">
            </div>
        </div>

    </div>
    <div class="rectangle ">
        <a href="{% url 'events:liveupdates' %}">
            <div class="campusam animation">
                LIVE UPDATES
            </div>
        </a>
    </div>

    <div id="FOOTER">
        <div class="icons-center">
            <div class="icons animation">
                <a href="https://www.facebook.com/taqneeqfest/" target="_blank">
                    <img src="{% static 'svg/facebook_icon.svg' %}">
                </a>
            </div>
            <div class="icons animation">
                <a href="https://www.instagram.com/taqneeqfest/" target="_blank">
                    <img src="{% static 'svg/insta.svg' %}">
                </a>
            </div>
            <div class="icons animation" style="margin-left: 0;">
                <a href="https://www.youtube.com/channel/UChCogXJ_-UmsMsCE3WY_PNQ" target="_blank">
                    <img src="{% static 'svg/youtube.svg' %}">
                </a>
            </div>
        </div>
    </div>
</body>

<script src="{% static 'js/jquery-3.5.1.min.js' %} "></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js " integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin=" anonymous "></script>


<script>
    function getcore() {

        allDept = {
            "Supercore": "Super Core",
            "Admin": "Admin",
            "AGM": "Artist & Guest Managament",
            "DC": "Digital Creatives",
            "Events": "Events",
            "Informals": "Informals",
            "Logistics": "Logistics",
            "Marketing": "Marketing",
            "Photography": "Photography",
            "Publicity": "Publicity",
            "SMCW": "Social Media & Content Writing",
            "Workshops": "Workshops",
            "TS": "Tech Support"
        }


        $.getJSON('all/', function(items) {
            for (var i = 0; i < items.length; i++) {
                try {
                    var tabName = items[i].fields.deptName;
                    var dataTab = document.getElementById(tabName);

                    var core = document.createElement('div');
                    core.classList.add('core-item');
                    core.classList.add('animated2s');
                    core.classList.add('fadeIn');

                    var coreBlock = document.createElement('div');
                    coreBlock.classList.add('coreBlock');

                    var coreImage = document.createElement('div');
                    coreImage.classList.add('coreImage');

                    var coreImg = document.createElement('div');
                    coreImg.classList.add('coreImg');

                    var image = document.createElement('img');
                    image.setAttribute('src', "{% static 'img/core/CoreName.webp' %}".replace('CoreName', items[i].fields.name));
                    coreImg.appendChild(image);

                    var coreGif = document.createElement('div');
                    coreGif.classList.add('coreGif');
                    coreGif.style.display = "none";

                    var image2 = document.createElement('img');
                    image2.setAttribute('src', "" + items[i].fields.gifurl);
                    coreGif.appendChild(image2);

                    coreImage.appendChild(coreImg);
                    coreImage.appendChild(coreGif);

                    var coreInfo = document.createElement('div');
                    coreInfo.classList.add('coreInfo');

                    var coreName = document.createElement('div');
                    coreName.classList.add('coreName');

                    coreName.innerHTML = items[i].fields.name;
                    coreInfo.appendChild(coreName);

                    var corePost = document.createElement('div');
                    corePost.classList.add('corePost');

                    corePost.innerHTML = items[i].fields.position;
                    coreInfo.appendChild(corePost);

                    coreBlock.appendChild(coreImage);
                    coreBlock.appendChild(coreInfo);
                    core.appendChild(coreBlock);
                    dataTab.appendChild(core);
                } catch (err) {
                    console.log(err);
                }
            }
        });

    }

    function hoverin() {
        document.getElementsByClassName('coreImg').style.display = 'none';
        document.getElementsByClassName('coreGif').style.display = 'block';
    }

    setTimeout(function() {
        $('.coreImage').hover(function() {
            $(this).find('.coreImg').hide();
            $(this).find('.coreGif').show();
        }, function() {
            $(this).find('.coreGif').hide();
            $(this).find('.coreImg').show();
        });
    }, 2000);
</script>

<script src="{% static 'js/core.js' %} "></script>

</html>

events/templates/events/bingo.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static '/css/elements_bingo.css' %}">
	<script src="elementsarray.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> 
	<script type="text/javascript" src="{% static '/js/elements_bingo.js' %}" defer></script>
</head>
<body>
	<div class="messagesOuter">
		<div id="questions"></div>
		<div id="noOfTries"></div>
		<div id="message"></div>
	</div>
	
	<div class="buttonOuter">
		<button class="buttons" type="button" id="play">Get a clue!</button>
		<button class="buttons" type="button" id="reset">Reset</button>
	</div>
	
	<div id="bingoHeadOuter" class="bingo">
		<table class="bingoSquares">
			<th class="bingoHead">B</th>
			<th class="bingoHead">I</th>
			<th class="bingoHead">N</th>
			<th class="bingoHead">G</th>
			<th class="bingoHead">O</th>
		</table>
	</div>
	
	<div class="bingo">
		<table class="bingoSquares" id="bingoboard"></table>
	</div>

</body>
</html>

events/templates/events/events.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1">
    <title>Events | Taqneeq 13.0</title>
    <!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

    <link rel="shortcut icon" href="{% static 'img/tq_logo.png' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="{% static '/css/events.css' %}">
    <link rel="stylesheet" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static '/css/menu.css' %}">
    <link rel="stylesheet" href="{% static '/css/events-modal.css' %}">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300&display=swap" rel="stylesheet">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <style>
        div.planet_description>label>a {
            text-decoration: none;
        }
        
        .menu-main::before {
            top: 12%;
        }
        
        .space {
            position: fixed;
            width: 100vw;
            height: 100vh;
            background-image: url("{% static 'img/17494.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }
        
        html,
        body {
            margin: 0;
            padding: 0;
            overflow: hidden;
            position: relative;
        }
        
        @media (max-width: 767px) {
            html,
            body {
                margin: 0;
                padding: 0;
                overflow-y: hidden;
                overflow-x: auto;
                position: relative;
            }
        }
        
        #loader {
            position: absolute;
            width: 100vw;
            height: 100vh;
            background-color: black;
            z-index: 99999;
        }
    </style>
</head>

<body>

    <div id="loader"></div>

    <script>
        setTimeout(function() {
            var loader = document.getElementById('loader');
            $("#loader").fadeOut("slow");
        }, 2000);
    </script>

    <!-- <script>
        $("p").click(function() {
            $("p").fadeOut("slow");
        });
    </script> -->

    <div class="space"></div>

    <h1 class="top-logo">
        <img src="{% static 'img/taqneeqpatterntq.png' %}" alt="" class="tqFullDesign">
    </h1>

    <!-- Menu -->
    <nav>
        <div class="menu-main">
            <div class="bar1 longanimbase longanim"></div>
            <div class="bar2 longanimbase longanim2"></div>
            <div class="bar3 longanimbase longanim3"></div>
        </div>
        <ul class="nav-links">
            <li id="li1"><a class=" menuAfterClick1" href="{% url 'main:landing-page' %}">Home</a></li>
            <li>
                <a class="menuAfterClick3" href="#"></a>
            </li>
            <li><a class="menuAfterClick4" href="{% url 'events:ourevents' %}"> Events</a></li>
            <li><a class="menuAfterClick2" href="{% url 'events:liveupdates' %}">Event Schedule</a></li>

            <!-- <li><a class="menuAfterClick5" href="#con">Contact Us</a></li> -->
            <li>
                <a class="menuAfterClick5" href="#"></a>
            </li>
            <li><a class="menuAfterClick6" href="{% url 'core:teams-page' %}">Our Team</a></li>
            <li>
                <a class="menuAfterClick7" href="#"></a>
            </li>
        </ul>
        <script src="{% static 'js/menu.js' %}"></script>
    </nav>
    <!-- Menu -->


    <!-- Planet-LeftMenu -->
    <input checked='checked' class='planet4' id='uranus' name='planet' type='radio'>
    <label class='planet-menu uranus' for='uranus'>
        <div class='preview'></div>
        <div class='info'>
            <h2>
                <div class='pip'></div>
                Workshops
            </h2>
        </div>
    </label>
    <input checked='checked' class='planet3' id='neptune' name='planet' type='radio'>
    <label class='planet-menu neptune' for='neptune'>
        <div class='preview'></div>
        <div class='info'>
            <h2>
                <div class='pip'></div>
                Informals
            </h2>
        </div>
    </label>
    <input checked='checked' class='planet2' id='saturn' name='planet' type='radio'>
    <label class='planet-menu saturn' for='saturn'>
        <div class='preview'></div>
        <div class='info'>
            <h2>
                <div class='pip'></div>
                Photography
            </h2>
        </div>
    </label>
    <input checked='checked' class='planet1' id='earth' name='planet' type='radio'>
    <label class='planet-menu earth' for='earth'>
        <div class='preview'></div>
        <div class='info'>
            <h2>
                <div class='pip'></div>
                Events
            </h2>
        </div>
    </label>
    <!-- /Planet-LeftMenu -->


    <!-- Solar-System -->
    <div class='solar'>
        <div class='solar_systm'>
            <div class='planet earth'>
                <div class='trajectory m'></div>
                <div class='planet_description earth'>
                    <h2></h2>
                    <h1>Events</h1>
                    <br>
                    <p>Events aimed at imparting technical and problem solving experience in the form of fun activities.</p>
                    <br><br>
                    <label for='readEarth'>
                        <a href="{% url 'events:event-view' 'events' %}">
                            Check it out
                        </a>
                    </label>
                </div>
                <div class='overlay'></div>
            </div>
        </div>
        <div class='solar_systm'>
            <div class='planet saturn'>
                <div class='moon titan'>
                    <h3>Moon</h3>
                    <h2>PHOEBOS</h2>

                </div>
                <div class='moon dione'>
                    <h3>Moon</h3>
                    <h2>DEIMOS</h2>
                </div>
                <div class='trajectory ti'></div>
                <div class='trajectory di'></div>
                <div class='trajectory enc'></div>
                <div class='planet_description saturn'>
                    <h2></h2>
                    <h1>Photography</h1>
                    <br>
                    <p>These events are aimed at throwing light on and teaching new, improved techniques for photography.</p>
                    <br><br>
                    <label for='readSaturn'>
                        <a href="{% url 'events:event-view' 'photography' %}">
                            Check it out
                        </a>
                    </label>
                </div>
                <div class='overlay'></div>
            </div>
        </div>
        <div class='solar_systm'>
            <div class='planet neptune'>
                <div class='moon triton'>
                    <h3>Moon</h3>
                    <h2>Triton</h2>
                </div>
                <div class='moon proteus'>
                    <h3>Moon</h3>
                    <h2>Proteus</h2>
                </div>
                <div class='moon nereid'>
                    <h3>Moon</h3>
                    <h2>Nereid</h2>
                </div>
                <div class='trajectory tri'></div>
                <div class='trajectory pro'></div>
                <div class='trajectory ner'></div>
                <div class='planet_description neptune'>
                    <h2></h2>
                    <h1>Informals</h1>
                    <br>
                    <p>Recreational events for participants to let loose.</p>
                    <br><br>
                    <label for='readNeptune'>
                        <a href="{% url 'events:event-view' 'informals' %}">
                            Check it out
                        </a>
                    </label>
                </div>
                <div class='overlay'></div>
            </div>
        </div>
        <div class='solar_systm'>
            <div class='planet uranus'>
                <div class='moon miranda'>
                    <h3>Moon</h3>
                    <h2>Miranda</h2>
                </div>
                <div class='moon ariel'>
                    <h3>Moon</h3>
                    <h2>Ariel</h2>
                </div>
                <div class='moon umbriel'>
                    <h3>Moon</h3>
                    <h2>Umbriel</h2>
                </div>
                <div class='trajectory mir'></div>
                <div class='trajectory ari'></div>
                <div class='trajectory umb'></div>
                <div class='planet_description uranus'>
                    <h2></h2>
                    <h1>Workshops</h1>
                    <br>
                    <p>These events involve educational seminars pertaining to high level technology.</p>
                    <br><br>
                    <label for='readUranus'>
                        <a href="{% url 'events:event-view' 'workshop' %}">
                            Check it out
                        </a>
                    </label>
                </div>
                <div class='overlay'></div>
            </div>
        </div>
    </div>
    <!-- /Solar-System -->

</body>


<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
<script src="{% static 'js/events-modal.js' %}"></script>

<script>
    window.onload = function() {
        if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1) {
            var elements = document.getElementsByTagName('br');
            for (var i = 0; i < elements.length; i++) {
                elements[i].style.display = 'none';
            }
        }
    }
</script>

<script>
    function getevent(eventSlug) {
        $.getJSON('/' + eventSlug, function(items) {
            console.log("asdasd");
            for (var i = 0; i < items.length; i++) {
                console.log(i);
            }
        });
    }
</script>



</html>

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Taqneeq13.0</title>
    <!--[if IE]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

    <link rel="shortcut icon" href="{% static 'img/tq_logo.png' %}">

    <script src="{% static 'js/jquery-3.5.1.min.js' %} "></script>

    <link rel="stylesheet" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static '/css/menu.css' %}">

    <link rel="preconnect" href="https://fonts.gstatic. com">
    <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300&display=swap" rel="stylesheet">

    <style>
        .menu-main::before {
            top: 12%;
        }
        
        .space {
            position: fixed;
            width: 100vw;
            height: 100vh;
            background-image: url("{% static 'img/17494.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }
        
        html,
        body {
            margin: 0;
            padding: 0;
            overflow: hidden;
            position: relative;
        }
        
        .rectangle a {
            text-decoration: none !important;
        }
        
        @media (max-width: 767px) {
            html,
            body {
                margin: 0;
                padding: 0;
                overflow-y: hidden;
                overflow-x: auto;
                position: relative;
            }
        }
        
        @media only screen and (max-width: 480px) {
            .rectangle {
                bottom: 4vw;
            }
            #FOOTER {
                bottom: 13vw;
            }
        }
    </style>
    {% block head %}{% endblock %}

</head>

<body>
    <div class="space"></div>

    <!-- <a href="#" class="no-line logotype"><img src="{% static 'img/tq_logo.png' %}" alt="" class="tqSmallLogo"></a> -->

    <!-- Menu -->
    <nav>
        <div class="menu-main">
            <div class="bar1 longanimnd"></div>
            <div class="bar2 longanimnd2"></div>
            <div class="bar3 longanimnd3"></div>
        </div>
        <ul class="nav-links">
            <li id="li1"><a class=" menuAfterClick1" href="{% url 'main:landing-page' %}">Home</a></li>
            <li>
                <a class="menuAfterClick3" href="#"></a>
            </li>
            <li><a class="menuAfterClick4" href="{% url 'events:ourevents' %}"> Events</a></li>
            <li><a class="menuAfterClick2" href="{% url 'events:liveupdates' %}">Event Schedule</a></li>

            <!-- <li><a class="menuAfterClick5" href="#con">Contact Us</a></li> -->
            <li>
                <a class="menuAfterClick5" href="#"></a>
            </li>
            <li><a class="menuAfterClick6" href="{% url 'core:teams-page' %}">Our Team</a></li>
            <li>
                <a class="menuAfterClick7" href="#"></a>
            </li>
        </ul>
    </nav>
    <!-- Menu -->

    {% block content %}{% endblock %}


    <div class="rectangle" style="box-sizing: content-box;">
        <a href="{% url 'events:liveupdates' %}">
            <div class="campusam animation">
                LIVE UPDATES
            </div>
        </a>
    </div>
</body>


<script src="{% static 'js/menu.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>

{% block js %} {% endblock %}

</html>